// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pablo_Burgos_Ap1_p2.DAL;

#nullable disable

namespace Pablo_Burgos_Ap1_p2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Pablo_Burgos_Ap1_p2.Entidades.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaDeVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ganancia")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Peso")
                        .HasColumnType("REAL");

                    b.Property<float>("PesoTotal")
                        .HasColumnType("REAL");

                    b.Property<float>("Precio")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorInventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Pablo_Burgos_Ap1_p2.Entidades.ProductosDetalle", b =>
                {
                    b.Property<int>("ProductosDetallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<float>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductosDetallesId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosDetalles");
                });

            modelBuilder.Entity("Pablo_Burgos_Ap1_p2.Entidades.ProductosEmpacados", b =>
                {
                    b.Property<int>("ProductoEmpacadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductosDetallesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidadProducidos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidadUtilizados")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoEmpacadosId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProductosDetallesId");

                    b.ToTable("ProductosEmpacados");
                });

            modelBuilder.Entity("Pablo_Burgos_Ap1_p2.Entidades.ProductosEmpacadosDetalle", b =>
                {
                    b.Property<int>("ProductoEmpacadosDetallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<float>("Peso")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductoEmpacadosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoEmpacadosDetallesId");

                    b.HasIndex("ProductoEmpacadosId");

                    b.ToTable("ProductosEmpacadosDetalle");
                });

            modelBuilder.Entity("Pablo_Burgos_Ap1_p2.Entidades.ProductosDetalle", b =>
                {
                    b.HasOne("Pablo_Burgos_Ap1_p2.Entidades.Productos", null)
                        .WithMany("ProductosDetalle")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pablo_Burgos_Ap1_p2.Entidades.ProductosEmpacados", b =>
                {
                    b.HasOne("Pablo_Burgos_Ap1_p2.Entidades.Productos", null)
                        .WithMany("ProductosEmpacados")
                        .HasForeignKey("ProductoId");

                    b.HasOne("Pablo_Burgos_Ap1_p2.Entidades.ProductosDetalle", null)
                        .WithMany("ProductosEmpacados")
                        .HasForeignKey("ProductosDetallesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pablo_Burgos_Ap1_p2.Entidades.ProductosEmpacadosDetalle", b =>
                {
                    b.HasOne("Pablo_Burgos_Ap1_p2.Entidades.ProductosEmpacados", null)
                        .WithMany("ProductosEmpacadosDetalle")
                        .HasForeignKey("ProductoEmpacadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pablo_Burgos_Ap1_p2.Entidades.Productos", b =>
                {
                    b.Navigation("ProductosDetalle");

                    b.Navigation("ProductosEmpacados");
                });

            modelBuilder.Entity("Pablo_Burgos_Ap1_p2.Entidades.ProductosDetalle", b =>
                {
                    b.Navigation("ProductosEmpacados");
                });

            modelBuilder.Entity("Pablo_Burgos_Ap1_p2.Entidades.ProductosEmpacados", b =>
                {
                    b.Navigation("ProductosEmpacadosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
